### ISSUE TITLE
Error on data after account creation

### ISSUE THREAD

**Issue by avizuber-zz** [paralin/angularjsauthseed#1]
Thanks for putting this code together.

When I create a new user I am automatically logged in, but the content page is unable to pick up my data. I need to log out and then log in again to get it. Any ideas on where I should look to fix this? Thanks!

**Comment by avizuber-zz** [comment]
Changing line 38 to $_SESSION['sessionId'] = $username; in createaccount.php fixes it.

**Comment by paralin** [comment]
If you can make a pull request, I'll update it. I don't really use angular anymore so let me know.
